### ISSUE TITLE
New bug for 3.0.0

### ISSUE THREAD

**Issue by doggy8088** [mysticmind/reversemarkdown-net#29]
I tested the following html.  The result is not good.

```html
<div>
  <table>
    <tbody>
      <tr>
        <td>aaa</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
      </tr>
      <tr>
        <td>6</td>
        <td>7</td>
        <td>8</td>
        <td>9</td>
        <td>9</td>
      </tr>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
      </tr>
      <tr>
        <td>7</td>
        <td>7</td>
        <td>8</td>
        <td>9</td>
        <td>0</td>
      </tr>
    </tbody>
  </table>
</div>
```

Actual result:

```md
|  |  |  |  |  |
| --- | --- | --- | --- | --- |
| aaa | 2 | 3 | 4 | 5 |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |
```

|  |  |  |  |  |
| --- | --- | --- | --- | --- |
| aaa | 2 | 3 | 4 | 5 |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |

Expected result:

```md
| aaa | 2 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |
```

| aaa | 2 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |

**Comment by mysticmind** [comment]
@doggy8088 I will look at providing an config option for handling header row. Essentially a config for `HeaderRow` with the following options:
- `HeaderRowOption.Default` : When there is row with `th` then it will be marked as header row. When there is no `th`, header row won't be added 
- HeaderRowOption.EmptyRow : Add an empty row when there is no row with`th` tags
- HeaderRowOption.FirstRow: Make first row the header row when there is row with `th` tags

The above will make it configurable for users to choose what the need.

**Comment by doggy8088** [comment]
I think `Default` should meet the majority markdown implementation.  If no `th` in the table, the header row should be added.

For example:

```html
  <table>
    <tbody>
      <tr>
        <td>aaa</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
      </tr>
      <tr>
        <td>6</td>
        <td>7</td>
        <td>8</td>
        <td>9</td>
        <td>9</td>
      </tr>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
      </tr>
      <tr>
        <td>7</td>
        <td>7</td>
        <td>8</td>
        <td>9</td>
        <td>0</td>
      </tr>
    </tbody>
  </table>
```

The default output should be:

```md
| aaa | 2 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |
```

| aaa | 2 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |

**Comment by mysticmind** [comment]
@doggy8088 Quick note, I will look at this sometime next week. Day job has been quite hectic and busy with too much activity.

**Comment by mysticmind** [comment]
@doggy8088 I have implemented the changes as below:
There are 2 options:
1. `TableWithoutHeaderRowHandlingOption.Default` - By default, the first row will be used as header row
2. `TableWithoutHeaderRowHandlingOption..EmptyRow` - An empty row will be added as the header row

The changes will be available in 3.1.0

**Comment by mysticmind** [comment]
Fixed.

**Comment by mysticmind** [comment]
@doggy8088 v3.1.0 released to NuGet, please take a look and confirm.

**Comment by doggy8088** [comment]
@mysticmind Do you have breaking changes? My code (`ReverseMarkdown.Config(...)` is not able to build now.

```cs
var html = Rtf.ToHtml(rtf);

bool githubFlavored = true;
bool removeComments = true;
var config = new ReverseMarkdown.Config(ReverseMarkdown.Config.UnknownTagsOption.PassThrough, githubFlavored : githubFlavored, removeComments : removeComments);
var converter = new ReverseMarkdown.Converter(config);

// var converter = new ReverseMarkdown.Converter();

var markdown = converter.Convert(html);
```

**Comment by doggy8088** [comment]
The result still not right. 😓

Here is my HTML snippet:

```html
<div style="font-size:12pt;font-family:&quot;Times New Roman&quot;, serif;"><table style="font-size:12pt;box-sizing:border-box;border-spacing:0;margin:0 0 0 0.3px;"><colgroup><col style="width:110.6px"><col style="width:110.6px"><col style="width:110.6px"><col style="width:110.6px"><col style="width:110.7px"></colgroup><tr><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">aaa</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">2</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">3</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">4</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">5</td></tr><tr><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">6</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">7</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">8</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">9</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">9</td></tr><tr><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">1</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">2</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">3</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">4</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">5</td></tr><tr><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">7</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">7</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">8</td><td style="text-align:left;font-family:Calibri, sans-serif;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">9</td><td style="text-align:left;vertical-align:top;border:1px solid;padding:0 7.2px 0 7.2px;">0</td></tr></table></div>
```

Here is my code:

```cs

bool githubFlavored = true;
bool removeComments = true;
var config = new ReverseMarkdown.Config
{
    UnknownTags = Config.UnknownTagsOption.PassThrough, // Include the unknown tag completely in the result (default as well)
    GithubFlavored = githubFlavored, // generate GitHub flavoured markdown, supported for BR, PRE and table tags
    RemoveComments = removeComments, // will ignore all comments
    SmartHrefHandling = true, // remove markdown output for links where appropriate
    TableWithoutHeaderRowHandling = TableWithoutHeaderRowHandlingOption.Default
};
var converter = new ReverseMarkdown.Converter(config);

var markdown = converter.Convert(html);
```

Here is the actual result:

```markdown

| aaa | 2 | 3 | 4 | 5 |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |
```

The expected result should be:

```markdown

| aaa | 2 | 3 | 4 | 5 |
| --- | - | - | - | - |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |
```


| aaa | 2 | 3 | 4 | 5 |
| --- | - | - | - | - |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |

**Comment by mysticmind** [comment]
@doggy8088 let me check

**Comment by mysticmind** [comment]
@doggy8088 The html which you shared has `<colgroup><col><col></colgroup>` as the first row within table. I didn't account for this use case, will apply a fix shortly.

**Comment by mysticmind** [comment]
@doggy8088 I have done a bug fix release v3.2.0. You should be able to use it once NuGet catches up on it. Please check and keep me posted.

**Comment by doggy8088** [comment]
@mysticmind Problem solved. Thanks! 👍
